[package]
name = "slog-scope-stdlog"
version = "0.2.0"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
description = "Standard Rust log crate adapter to slog-rs"
keywords = ["slog", "logging", "json", "log"]
license = "MPL-2.0"
documentation = "https://docs.rs/slog-scope-stdlog"
homepage = "https://github.com/slog-rs/scope-stdlog"
repository = "https://github.com/slog-rs/scope-stdlog"
readme = "README.md"

[lib]
path = "lib.rs"

[dependencies]
slog = "1.1"
slog-scope = "0.2.2"
slog-term = "1.3"
log = "0.3.6"
crossbeam = "0.2.9"
